"""
Fixed-Depth ResNet Autoencoder — v7
====================================
Standard convolutional autoencoder with NO gates, NO bypass constants.

The only variable is depth: n_blocks ∈ {1, 2, 3, 4} residual blocks
in both encoder and decoder. All other hyperparameters are fixed.

This is the clean architecture for the Fixed-Depth Comparison experiment
(Option 2 from Stop_and_think_v1.pdf). The prediction from Poggio et al.
(2016, 2017): deeper networks should outperform shallower ones on data
generated by deeper compositional processes.

Author: G. Ruffini / Technical Note companion code — v7
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Tuple


# ═══════════════════════════════════════════════════════════
# Standard residual block — no gates, no bypass
# ═══════════════════════════════════════════════════════════

class ResBlock(nn.Module):
    """Standard residual block: h' = ReLU(h + F(h))."""
    def __init__(self, channels: int):
        super().__init__()
        self.conv1 = nn.Conv2d(channels, channels, 3, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(channels)
        self.conv2 = nn.Conv2d(channels, channels, 3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(channels)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        residual = F.relu(self.bn1(self.conv1(x)))
        residual = self.bn2(self.conv2(residual))
        return F.relu(x + residual)


# ═══════════════════════════════════════════════════════════
# Encoder — fully convolutional, depth-parameterised
# ═══════════════════════════════════════════════════════════

class Encoder(nn.Module):
    """
    Fully convolutional encoder with variable depth.

    Architecture:
      stem (1×1 conv) → [ResBlock × n_blocks] → downsample →
      [ResBlock × n_blocks] → downsample → ... → 1×1 to latent

    n_stages is fixed at 4 (giving 3 downsamples → 16× spatial reduction).
    n_blocks controls the number of ResBlocks per stage (the depth knob).
    """
    def __init__(
        self,
        img_size: int = 128,
        latent_dim: int = 8,
        base_channels: int = 32,
        n_blocks: int = 2,
        n_stages: int = 4,
    ):
        super().__init__()
        self.n_stages = n_stages
        self.n_blocks = n_blocks

        # Stem: 1×1 conv
        self.stem = nn.Sequential(
            nn.Conv2d(3, base_channels, 1, bias=False),
            nn.BatchNorm2d(base_channels),
            nn.ReLU(),
        )

        self.stages = nn.ModuleList()
        self.downsamples = nn.ModuleList()
        ch = base_channels

        for stage in range(n_stages):
            blocks = nn.Sequential(*[ResBlock(ch) for _ in range(n_blocks)])
            self.stages.append(blocks)

            if stage < n_stages - 1:
                next_ch = ch * 2
                self.downsamples.append(nn.Sequential(
                    nn.AvgPool2d(2),
                    nn.Conv2d(ch, next_ch, 1, bias=False),
                    nn.BatchNorm2d(next_ch),
                    nn.ReLU(),
                ))
                ch = next_ch
            else:
                self.downsamples.append(nn.Identity())

        self.final_channels = ch

        # 1×1 conv to latent channels
        self.to_latent = nn.Sequential(
            nn.Conv2d(ch, latent_dim, 1, bias=False),
            nn.BatchNorm2d(latent_dim),
        )
        self.latent_dim = latent_dim

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h = self.stem(x)
        for stage_idx, (blocks, down) in enumerate(
            zip(self.stages, self.downsamples)
        ):
            h = blocks(h)
            if stage_idx < self.n_stages - 1:
                h = down(h)
        z = self.to_latent(h)
        return z


# ═══════════════════════════════════════════════════════════
# Decoder — fully convolutional, with residual blocks
# ═══════════════════════════════════════════════════════════

class Decoder(nn.Module):
    """
    Fully convolutional decoder with residual blocks.

    Mirrors the encoder: latent → 1×1 expand → [ResBlock × n_blocks] →
    upsample → [ResBlock × n_blocks] → ... → 1×1 to RGB.

    Adding ResBlocks in the decoder ensures that depth affects both
    encoding and decoding capacity symmetrically.
    """
    def __init__(
        self,
        img_size: int = 128,
        latent_dim: int = 8,
        base_channels: int = 32,
        n_blocks: int = 2,
        n_stages: int = 4,
    ):
        super().__init__()
        self.n_stages = n_stages

        final_ch = base_channels * (2 ** (n_stages - 1))

        # 1×1 from latent to decoder channels
        self.from_latent = nn.Sequential(
            nn.Conv2d(latent_dim, final_ch, 1, bias=False),
            nn.BatchNorm2d(final_ch),
            nn.ReLU(),
        )

        # ResBlocks + upsample stages
        self.stages = nn.ModuleList()
        self.channel_reduce = nn.ModuleList()
        ch = final_ch

        # First stage (no upsample) — process at lowest resolution
        self.stages.append(nn.Sequential(*[ResBlock(ch) for _ in range(n_blocks)]))

        for stage in range(n_stages - 1):
            next_ch = ch // 2
            self.channel_reduce.append(nn.Sequential(
                nn.Conv2d(ch, next_ch, 1, bias=False),
                nn.BatchNorm2d(next_ch),
                nn.ReLU(),
            ))
            self.stages.append(nn.Sequential(*[ResBlock(next_ch) for _ in range(n_blocks)]))
            ch = next_ch

        self.to_rgb = nn.Sequential(
            nn.Conv2d(ch, 3, 1),
            nn.Sigmoid(),
        )

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        h = self.from_latent(z)
        h = self.stages[0](h)  # Process at lowest resolution

        for i, (reduce, stage) in enumerate(
            zip(self.channel_reduce, self.stages[1:])
        ):
            h = F.interpolate(h, scale_factor=2, mode='bilinear',
                              align_corners=False)
            h = reduce(h)
            h = stage(h)

        return self.to_rgb(h)


# ═══════════════════════════════════════════════════════════
# Full autoencoder
# ═══════════════════════════════════════════════════════════

class FixedDepthAutoencoder(nn.Module):
    """
    Standard autoencoder with parameterised depth.

    n_blocks controls the number of residual blocks per stage
    in both encoder and decoder.

    Total residual blocks = n_stages × n_blocks × 2 (enc + dec)
    Total convolution layers ≈ n_stages × n_blocks × 4 + stems
    """
    def __init__(
        self,
        img_size: int = 128,
        latent_dim: int = 8,
        base_channels: int = 32,
        n_blocks: int = 2,
        n_stages: int = 4,
    ):
        super().__init__()
        self.n_blocks = n_blocks
        self.n_stages = n_stages
        self.encoder = Encoder(
            img_size=img_size,
            latent_dim=latent_dim,
            base_channels=base_channels,
            n_blocks=n_blocks,
            n_stages=n_stages,
        )
        self.decoder = Decoder(
            img_size=img_size,
            latent_dim=latent_dim,
            base_channels=base_channels,
            n_blocks=n_blocks,
            n_stages=n_stages,
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        z = self.encoder(x)
        x_recon = self.decoder(z)
        return x_recon

    def count_parameters(self) -> int:
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    @property
    def total_blocks(self) -> int:
        """Total residual blocks (encoder + decoder)."""
        return self.n_stages * self.n_blocks * 2
